<?php


namespace app\models;
use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public static function tableName()
    {
        return 'pm_videos'; // TODO: Change the autogenerated stub
    }
    public function gatCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}